using System.Collections.Generic;
using UnityEngine;

namespace MochiMeadows.Art
{
    // All game art, defined as ASCII pixel art.
    public static class SpriteBank
    {
        public static Sprite PlayerDown0, PlayerDown1, PlayerUp0, PlayerUp1, PlayerSide0, PlayerSide1;
        public static Sprite MochiIdle, MochiWalk0, MochiWalk1;
        public static Sprite Grass0, Grass1, Grass2, Path0, Soil0, Soil1, SoilWet, Fence0, Fence1, Pond0, Pond1, Pond2, Pond3, WaterTile;
        public static Sprite Flower0, Flower1, Flower2, Daisy;
        public static Sprite TreeBlossom, TreeTrunkTile, Blanket;
        public static Sprite Sun, Moon, Star, Cloud, Zzz;
        public static Sprite ShopStand;
        public static Sprite QuestBoard, LockedTile, Deed;
        public static Sprite Coin, Heart, HeartPink, Sparkle, WaterDrop, MusicNote;
        public static Sprite Strawberry0, Strawberry1, Strawberry2, Strawberry3;
        public static Sprite Blueberry0, Blueberry1, Blueberry2, Blueberry3;
        public static Sprite Pumpkitten0, Pumpkitten1, Pumpkitten2, Pumpkitten3;
        public static Sprite Sakura0, Sakura1, Sakura2, Sakura3;
        public static Sprite Melon0, Melon1, Melon2, Melon3;
        public static Sprite MochiRice0, MochiRice1, MochiRice2, MochiRice3;
        public static Sprite HoeIcon, CanIcon, HandIcon;
        public static Sprite[,] CropSprites;
        public static Sprite Chicken0, Chicken1, Chicken2;
        public static Sprite ChickenPink0, ChickenPink1, ChickenPink2;
        public static Sprite Goldfish, BubbleFish, SakuraFish;
        public static Sprite Egg, KitchenTable, Lantern, Gnome, Beehive, Honey;

        static Dictionary<char, Color> PlayerPal, MochiPal, TilePal, CropPal, SkyPal, ItemPal, ChickenPal, ChickenPinkPal, FishPal;

        static readonly string[] ArtDown0 =
        {
            "................", ".......h........", "....hhhhhhhh....", "...hhhhhhhhhh...",
            "..hhhccccccchhh..", "..hhckwccwkchh..", "..hhckwccwkchh..", "..hhcbbccbbchh..",
            "..hhcccccccchh..", "..hhhccccccchhh.", "....cccccccc....", "..cppppppppppc..",
            "..pppppppppppp..", "..pppppppppppp..", "..pppppppppppp..", "...ss...ss......",
            "...ss...ss......",
        };
        static readonly string[] ArtDown1 =
        {
            "................", ".......h........", "....hhhhhhhh....", "...hhhhhhhhhh...",
            "..hhhccccccchhh..", "..hhckwccwkchh..", "..hhckwccwkchh..", "..hhcbbccbbchh..",
            "..hhcccccccchh..", "..hhhccccccchhh.", "....cccccccc....", "..cppppppppppc..",
            "..pppppppppppp..", ".ppppppppppppp..", ".ppppppppppppp..", "..ss.....ss.....",
            "..ss......ss....",
        };
        static readonly string[] ArtUp0 =
        {
            "................", ".......h........", "....hhhhhhhh....", "...hhhhhhhhhh...",
            "...hhhhhhhhhh...", "..hhhhPwwPhhhh..", "..hhhPPPPPPPhhh..", "..hhhhhhhhhhhh..",
            "..hhhhhhhhhhhh..", "..hhhccccccchhh.", "....cccccccc....", "..cppppppppppc..",
            "..pppppppppppp..", "..pppppppppppp..", "..pppppppppppp..", "...ss...ss......",
            "...ss...ss......",
        };
        static readonly string[] ArtUp1 =
        {
            "................", ".......h........", "....hhhhhhhh....", "...hhhhhhhhhh...",
            "...hhhhhhhhhh...", "..hhhhPwwPhhhh..", "..hhhPPPPPPPhhh..", "..hhhhhhhhhhhh..",
            "..hhhhhhhhhhhh..", "..hhhccccccchhh.", "....cccccccc....", "..cppppppppppc..",
            "..pppppppppppp..", ".ppppppppppppp..", ".ppppppppppppp..", "..ss.....ss.....",
            "..ss......ss....",
        };
        static readonly string[] ArtSide0 =
        {
            "................", ".......h........", "....hhhhhhhh....", "...hhhhhhhhhh...",
            "...hhhhccccchh..", "..hhhhckwwkchh..", "..hhhhckwwkchh..", "..hhhhcbbbbchh..",
            "..hhhhccccccchh.", "...hhcccccccchh.", "....cccccccc....", "..cppppppppppc..",
            "..pppppppppppp..", ".pppppppppppppp.", ".pppppppppppppp.", "...ss....ss.....",
            "...ss....ss.....",
        };
        static readonly string[] ArtSide1 =
        {
            "................", ".......h........", "....hhhhhhhh....", "...hhhhhhhhhh...",
            "...hhhhccccchh..", "..hhhhckwwkchh..", "..hhhhckwwkchh..", "..hhhhcbbbbchh..",
            "..hhhhccccccchh.", "...hhcccccccchh.", "....cccccccc....", "..cppppppppppc..",
            ".ppppppppppppp..", ".ppppppppppppp..", ".pppppppppppppp.", "..ss.....ss.....",
            "...ss......ss...",
        };

        public static Color DressColor = Palette.StrawberryPink;
        public static Color HairColor = Palette.Chocolate;

        // Rebuild the player sprites with a new outfit (called at boot and on makeover).
        public static void RebuildPlayerSprites(Color dress, Color hair)
        {
            DressColor = dress;
            HairColor = hair;
            var pal = new Dictionary<char, Color>
            {
                ['h'] = hair, ['H'] = Color.Lerp(hair, Color.black, 0.22f),
                ['c'] = Palette.Skin, ['k'] = Palette.EyePlum,
                ['w'] = Palette.White, ['b'] = Palette.Blush,
                ['p'] = dress, ['P'] = Color.Lerp(dress, Color.black, 0.18f),
                ['s'] = Palette.Cream, ['d'] = Color.Lerp(dress, Color.black, 0.28f),
            };
            PlayerDown0 = S("PlayerDown0", true, PlayerPal, ArtDown0);
            PlayerDown1 = S("PlayerDown1", true, PlayerPal, ArtDown1);
            PlayerUp0 = S("PlayerUp0", true, PlayerPal, ArtUp0);
            PlayerUp1 = S("PlayerUp1", true, PlayerPal, ArtUp1);
            PlayerSide0 = S("PlayerSide0", true, PlayerPal, ArtSide0);
            PlayerSide1 = S("PlayerSide1", true, PlayerPal, ArtSide1);
        }

        public static void BuildAll()
        {
            PlayerPal = new Dictionary<char, Color>
            {
                ['h'] = Palette.Chocolate, ['H'] = Palette.DarkChoco,
                ['c'] = Palette.Skin, ['k'] = Palette.EyePlum,
                ['w'] = Palette.White, ['b'] = Palette.Blush,
                ['p'] = Palette.StrawberryPink, ['P'] = Palette.DeepPink,
                ['s'] = Palette.Cream, ['d'] = Palette.Chocolate,
            };
            MochiPal = new Dictionary<char, Color>
            {
                ['w'] = Palette.White, ['c'] = Palette.Cream,
                ['p'] = Palette.PetalPink, ['k'] = Palette.EyePlum,
                ['o'] = Palette.Orange, ['g'] = Palette.Leaf,
                ['t'] = Palette.Peach,
            };
            TilePal = new Dictionary<char, Color>
            {
                ['g'] = Palette.Grass, ['G'] = Palette.GrassDark,
                ['p'] = Palette.Path, ['P'] = Palette.PathShade,
                ['s'] = Palette.Soil, ['S'] = Palette.SoilShade,
                ['w'] = Palette.Water, ['W'] = Palette.WaterDeep,
                ['o'] = Palette.WetSoil, ['O'] = Palette.WetSoilShade,
                ['d'] = Palette.Wood, ['D'] = Palette.WoodShade,
                ['l'] = Palette.Leaf, ['L'] = Palette.LeafDark,
                ['r'] = Palette.PetalPink, ['y'] = Palette.Yellow,
                ['f'] = Palette.Peach, ['t'] = Palette.TreeTrunk,
                ['n'] = Palette.NightSky,
            };
            CropPal = new Dictionary<char, Color>
            {
                ['l'] = Palette.Leaf, ['L'] = Palette.LeafDark,
                ['b'] = Palette.DeepPink, ['B'] = Palette.StrawberryPink,
                ['u'] = Palette.BabyBlue, ['U'] = Palette.Sky,
                ['o'] = Palette.Orange, ['O'] = Palette.Peach,
                ['s'] = Palette.Skin, ['k'] = Palette.EyePlum,
                ['c'] = Palette.Soil, ['r'] = Palette.PetalPink,
                ['R'] = Palette.Peach, ['w'] = Palette.White,
                ['y'] = Palette.Yellow, ['g'] = Palette.Grass,
                ['n'] = Palette.NightSky, ['G'] = Palette.GrassDark,
                ['m'] = Palette.Mint,
            };
            ChickenPal = new Dictionary<char, Color>
            {
                ['w'] = Palette.White, ['c'] = Palette.Cream,
                ['y'] = Palette.Yellow, ['r'] = Palette.DeepPink,
                ['o'] = Palette.Orange, ['k'] = Palette.EyePlum,
            };
            FishPal = new Dictionary<char, Color>
            {
                ['o'] = Palette.Orange, ['O'] = Palette.Peach,
                ['w'] = Palette.White, ['k'] = Palette.EyePlum,
                ['u'] = Palette.BabyBlue, ['U'] = Palette.Sky,
                ['r'] = Palette.PetalPink, ['R'] = Palette.DeepPink,
                ['b'] = Palette.Blush,
            };
            ChickenPinkPal = new Dictionary<char, Color>
            {
                ['w'] = Palette.PetalPink, ['c'] = Palette.White,
                ['y'] = Palette.Yellow, ['r'] = Palette.DeepPink,
                ['o'] = Palette.Orange, ['k'] = Palette.EyePlum,
            };
            SkyPal = new Dictionary<char, Color>
            {
                ['y'] = Palette.Yellow, ['c'] = Palette.Cream,
                ['n'] = Palette.StarGold, ['m'] = Palette.White,
            };
            ItemPal = new Dictionary<char, Color>
            {
                ['p'] = Palette.StrawberryPink, ['P'] = Palette.DeepPink,
                ['c'] = Palette.Cream, ['g'] = Palette.Leaf,
                ['b'] = Palette.BabyBlue, ['o'] = Palette.Orange,
                ['w'] = Palette.White, ['d'] = Palette.Wood,
                ['r'] = Palette.PetalPink, ['y'] = Palette.Yellow,
                ['k'] = Palette.EyePlum, ['W'] = Palette.Water,
            };

            PlayerDown0 = S("PlayerDown0", true, PlayerPal,
                "................",
                ".......h........",
                "....hhhhhhhh....",
                "...hhhhhhhhhh...",
                "..hhhcccccchhh..",
                "..hhckwccwkchh..",
                "..hhckwccwkchh..",
                "..hhcbbccbbchh..",
                "..hhcccccccchh..",
                "..hhhcccccchhh..",
                "....cccccccc....",
                "..cppppppppppc..",
                "..pppppppppppp..",
                "..pppppppppppp..",
                "..pppppppppppp..",
                "...ss...ss......",
                "...ss...ss......");

            PlayerDown1 = S("PlayerDown1", true, PlayerPal,
                "................",
                ".......h........",
                "....hhhhhhhh....",
                "...hhhhhhhhhh...",
                "..hhhcccccchhh..",
                "..hhckwccwkchh..",
                "..hhckwccwkchh..",
                "..hhcbbccbbchh..",
                "..hhcccccccchh..",
                "..hhhcccccchhh..",
                "....cccccccc....",
                "..cppppppppppc..",
                "..pppppppppppp..",
                ".ppppppppppppp..",
                ".ppppppppppppp..",
                "..ss.....ss.....",
                "..ss......ss....");

            PlayerUp0 = S("PlayerUp0", true, PlayerPal,
                "................",
                ".......h........",
                "....hhhhhhhh....",
                "...hhhhhhhhhh...",
                "...hhhhhhhhhh...",
                "..hhhhPwwPhhhh..",
                "..hhhPPPPPPhhh..",
                "..hhhhhhhhhhhh..",
                "..hhhhhhhhhhhh..",
                "..hhhcccccchhh..",
                "....cccccccc....",
                "..cppppppppppc..",
                "..pppppppppppp..",
                "..pppppppppppp..",
                "..pppppppppppp..",
                "...ss...ss......",
                "...ss...ss......");

            PlayerUp1 = S("PlayerUp1", true, PlayerPal,
                "................",
                ".......h........",
                "....hhhhhhhh....",
                "...hhhhhhhhhh...",
                "...hhhhhhhhhh...",
                "..hhhhPwwPhhhh..",
                "..hhhPPPPPPhhh..",
                "..hhhhhhhhhhhh..",
                "..hhhhhhhhhhhh..",
                "..hhhcccccchhh..",
                "....cccccccc....",
                "..cppppppppppc..",
                "..pppppppppppp..",
                ".ppppppppppppp..",
                ".ppppppppppppp..",
                "..ss.....ss.....",
                "..ss......ss....");

            PlayerSide0 = S("PlayerSide0", true, PlayerPal,
                "................",
                ".......h........",
                "....hhhhhhhh....",
                "...hhhhhhhhhh...",
                "...hhhhccccchh..",
                "..hhhhckwwkchh..",
                "..hhhhckwwkchh..",
                "..hhhhcbbbbchh..",
                "..hhhhccccccchh.",
                "...hhcccccccchh.",
                "....cccccccc....",
                "..cppppppppppc..",
                "..pppppppppppp..",
                ".pppppppppppppp.",
                ".pppppppppppppp.",
                "...ss....ss.....",
                "...ss....ss.....");

            PlayerSide1 = S("PlayerSide1", true, PlayerPal,
                "................",
                ".......h........",
                "....hhhhhhhh....",
                "...hhhhhhhhhh...",
                "...hhhhccccchh..",
                "..hhhhckwwkchh..",
                "..hhhhckwwkchh..",
                "..hhhhcbbbbchh..",
                "..hhhhccccccchh.",
                "...hhcccccccchh.",
                "....cccccccc....",
                "..cppppppppppc..",
                ".ppppppppppppp..",
                ".ppppppppppppp..",
                ".pppppppppppppp.",
                "..ss.....ss.....",
                "...ss......ss...");

            // --- Mochi the marshmallow cat (16x16) ---
            MochiIdle = S("MochiIdle", true, MochiPal,
                "................",
                "................",
                "....wwwwwwww....",
                "...wwwwwwwwww...",
                "..wppwwwwwwppw..",
                "..wppwwwwwwppw..",
                "..wwbkwccwkbww..",
                "..wwbkwccwkbww..",
                "..wwwwwwwwwwww..",
                "..wwwwwyywwwww..",
                "..wwwwwwwwwwww..",
                "..wwwwwwwwwwww..",
                ".wwwwwwwwwwwwww.",
                ".wwwwwwwwwwwwww.",
                "...ww...ww..ww..",
                "............wwww");

            MochiWalk0 = S("MochiWalk0", true, MochiPal,
                "................",
                "................",
                "....wwwwwwww....",
                "...wwwwwwwwww...",
                "..wppwwwwwwppw..",
                "..wppwwwwwwppw..",
                "..wwbkwccwkbww..",
                "..wwbkwccwkbww..",
                "..wwwwwwwwwwww..",
                "..wwwwwyywwwww..",
                "..wwwwwwwwwwww..",
                "..wwwwwwwwwwww..",
                ".wwwwwwwwwwwwww.",
                ".wwwwwwwwwwwwww.",
                "..ww....ww...ww.",
                "............wwww");

            MochiWalk1 = S("MochiWalk1", true, MochiPal,
                "................",
                "................",
                "....wwwwwwww....",
                "...wwwwwwwwww...",
                "..wppwwwwwwppw..",
                "..wppwwwwwwppw..",
                "..wwbkwccwkbww..",
                "..wwbkwccwkbww..",
                "..wwwwwwwwwwww..",
                "..wwwwwyywwwww..",
                "..wwwwwwwwwwww..",
                "..wwwwwwwwwwww..",
                ".wwwwwwwwwwwwww.",
                ".wwwwwwwwwwwwww.",
                "...ww...ww...ww.",
                "............wwww");

            // --- Tiles (16x16) ---
            Grass0 = S("Grass0", TilePal,
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg");

            Grass1 = S("Grass1", TilePal,
                "gggggggggggggggg",
                "gggggGgggggGgggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggGggggggggggGg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "ggggggGggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggGgggggggGgggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg");

            Grass2 = S("Grass2", TilePal,
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg");

            Path0 = S("Path0", TilePal,
                "pppppppppppppppp",
                "pppPppppppppPppp",
                "pppppppppppppppp",
                "pppppppppppppppp",
                "ppppPppppppppppp",
                "pppppppppppppppp",
                "pppppppppppppppp",
                "pPpppppppppppppp",
                "pppppppppppppppp",
                "pppppppppppPpppp",
                "pppppppppppppppp",
                "pppppppppppppppp",
                "pppPpppppppppppp",
                "pppppppppppppppp",
                "pppppppppppPpppp",
                "pppppppppppppppp");

            Soil0 = S("Soil0", TilePal,
                "ssssssssssssssss",
                "ssssssssssssssss",
                "sSSssSSssSSssSSs",
                "ssssssssssssssss",
                "ssssssssssssssss",
                "SSssSSssSSssSSss",
                "ssssssssssssssss",
                "ssssssssssssssss",
                "sSSssSSssSSssSSs",
                "ssssssssssssssss",
                "ssssssssssssssss",
                "SSssSSssSSssSSss",
                "ssssssssssssssss",
                "ssssssssssssssss",
                "sSSssSSssSSssSSs",
                "ssssssssssssssss");

            Soil1 = S("Soil1", TilePal,
                "ssssssssssssssss",
                "ssssssssssssssss",
                "ssSSssSSssSSssSs",
                "ssssssssssssssss",
                "ssssssssssssssss",
                "sSSssSSssSSssSSs",
                "ssssssssssssssss",
                "ssssssssssssssss",
                "SSssSSssSSssSSss",
                "ssssssssssssssss",
                "ssssssssssssssss",
                "sSSssSSssSSssSSs",
                "ssssssssssssssss",
                "ssssssssssssssss",
                "ssSSssSSssSSssSs",
                "ssssssssssssssss");

            SoilWet = S("SoilWet", TilePal,
                "oooooooooooooooo",
                "oooooooooooooooo",
                "oOOooOOooOOooOOo",
                "oooooooooooooooo",
                "oooooooooooooooo",
                "OOooOOooOOooOOoo",
                "oooooooooooooooo",
                "oooooooooooooooo",
                "oOOooOOooOOooOOo",
                "oooooooooooooooo",
                "oooooooooooooooo",
                "OOooOOooOOooOOoo",
                "oooooooooooooooo",
                "oooooooooooooooo",
                "oOOooOOooOOooOOo",
                "oooooooooooooooo");

            WaterTile = S("WaterTile", TilePal,
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwWwwwwwwWwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwWwwwwwwWwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwWwwwwwwwwwwWww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwWwwwwwwwwwwWww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwWwwwwwwWwwww",
                "wwwwwwwwwwwwwwww");

            Fence0 = S("Fence0", true, TilePal,
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "..ddd....ddd....",
                "..ddd....ddd....",
                "..ddd....ddd....",
                ".ddddd..ddddd...",
                ".ddddd..ddddd...",
                "................",
                "................");

            Fence1 = S("Fence1", true, TilePal,
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "....ddd..ddd....",
                "....ddd..ddd....",
                "....ddd..ddd....",
                "..ddddddddddd...",
                "..ddddddddddd...",
                "................",
                "................");

            Pond0 = S("Pond0", TilePal,
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwww");

            Pond1 = Pond0; Pond2 = Pond0; Pond3 = Pond0;

            Flower0 = S("Flower0", TilePal,
                "................",
                ".......r........",
                "......ryy.......",
                ".......r........",
                "................",
                ".......l........",
                "......lll.......",
                ".......l........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Flower1 = S("Flower1", TilePal,
                "......r.........",
                ".....ryy........",
                "......r.........",
                ".......l........",
                "......lll.......",
                ".......l........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Flower2 = S("Flower2", TilePal,
                "..........y.....",
                ".............y..",
                "..............y.",
                "......y......y..",
                "...........y....",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Daisy = S("Daisy", TilePal,
                "................",
                "................",
                "................",
                "......ww........",
                ".....wwww.......",
                ".....wwww.......",
                "......ww........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            // --- Blossom tree (24x28-ish, drawn as a 16x16 trunk + canopy built separately) ---
            TreeTrunkTile = S("TreeTrunkTile", true, TilePal,
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                ".....tttt.......",
                ".....tttt.......",
                "....tttttt......",
                "....tttttt......",
                "................",
                "................");

            Blanket = S("Blanket", true, TilePal,
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "..pppppppppppp..",
                "..pppppppppppp..",
                "..pppPPppPPppp..",
                "..pppppppppppp..",
                "..wwwwwwwwwwww..",
                "................");

            // --- Crops: 4 stages each (12x12 art, centered) ---
            Strawberry0 = S("Strawberry0", true, CropPal,
                ".....l...l......",
                "......lll.......",
                ".......l........",
                ".....llll.......",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Strawberry1 = S("Strawberry1", true, CropPal,
                ".....llll.......",
                "....llllll......",
                ".....llll.......",
                "......ll........",
                "....lllll.......",
                "...lll.lll......",
                "....ll.ll.......",
                ".....lll........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Strawberry2 = S("Strawberry2", true, CropPal,
                ".....llll.......",
                "....llllll......",
                ".....llll.......",
                "......ll........",
                "....lllll.......",
                "...lll.lll......",
                "....ll.ll.......",
                ".....bbb........",
                "....bbbbbb......",
                ".....bbbb.......",
                "......bb........",
                "................",
                "................",
                "................",
                "................",
                "................");

            Strawberry3 = S("Strawberry3", true, CropPal,
                ".....llll.......",
                "....llllll......",
                ".....llll.......",
                "......ll........",
                "....lllll.......",
                "...lll.lll......",
                "....ll.ll.......",
                "..bbbbbbbbbb....",
                ".bbBbbbbbbbbB...",
                ".bbbbbbbbbbbb...",
                "..bbbbbbbbbb....",
                "...bb.bb.bb.....",
                "................",
                "................",
                "................",
                "................");

            Blueberry0 = S("Blueberry0", true, CropPal,
                ".....ll.........",
                ".....ll.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Blueberry1 = S("Blueberry1", true, CropPal,
                "....llll........",
                "...llllll.......",
                "....llll........",
                "....l..l........",
                "....l..l........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Blueberry2 = S("Blueberry2", true, CropPal,
                "....llll........",
                "...llllll.......",
                "....llll........",
                "....l..l........",
                "....l..l........",
                "......u.........",
                "....uuuuu.......",
                ".....uuu........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Blueberry3 = S("Blueberry3", true, CropPal,
                "....llll........",
                "...llllll.......",
                "....llll........",
                "....l..l........",
                "....l..l........",
                "..u..u..u.......",
                ".uuuuuuuuu......",
                ".uuUuuuuUuu.....",
                "..uuuuuuuu......",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Pumpkitten0 = S("Pumpkitten0", true, CropPal,
                ".....ll.........",
                "......ll........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Pumpkitten1 = S("Pumpkitten1", true, CropPal,
                ".....ll.........",
                "....llll........",
                ".....ll.........",
                ".....ll.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Pumpkitten2 = S("Pumpkitten2", true, CropPal,
                "....llll........",
                "...ll..ll.......",
                "....llll........",
                ".....ll.........",
                ".....oo.........",
                "....oooo........",
                ".....oo.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Pumpkitten3 = S("Pumpkitten3", true, CropPal,
                "....llll........",
                "...ll..ll.......",
                "....llll........",
                ".....ll.........",
                "..oo..oo........",
                ".oo....oo.......",
                ".o kk oo........",
                ".oo..oo.........",
                "..oooooo........",
                "...o.oo.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Sakura0 = S("Sakura0", true, CropPal,
                "......rr........",
                ".....rRr........",
                "......rr........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Sakura1 = S("Sakura1", true, CropPal,
                "......rr........",
                ".....rRr........",
                "......rr........",
                ".......l........",
                ".......l........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Sakura2 = S("Sakura2", true, CropPal,
                ".....rrrr.......",
                "....rRrrRr......",
                ".....rrrr.......",
                ".......l........",
                "......lll.......",
                ".......l........",
                "......rrr.......",
                ".....rRrrR......",
                ".....rrrr.......",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Sakura3 = S("Sakura3", true, CropPal,
                ".....rrrr.......",
                "....rRrrRr......",
                ".....rrrr.......",
                ".......l........",
                "......lll.......",
                ".......l........",
                "....rrrrr.......",
                "...rRrrrrRr.....",
                "..rrRrrrrRrr....",
                "..rrrrrrrrrr....",
                "...rrrrrrrr.....",
                "................",
                "................",
                "................",
                "................",
                "................");

            // --- Melon (summer) ---
            Melon0 = S("Melon0", true, CropPal,
                ".....ll.........",
                "....llll........",
                ".....ll.........",
                ".....ll.........",
                "....llll........",
                ".....ll.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Melon1 = S("Melon1", true, CropPal,
                ".....ll.........",
                "....llll........",
                ".....ll.........",
                "....llll........",
                "...llllll.......",
                "....llll........",
                "...ll.ll........",
                "...ll.ll........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Melon2 = S("Melon2", true, CropPal,
                ".....ll.........",
                "....llll........",
                ".....ll.........",
                "...llllll.......",
                "....llll........",
                "......G.........",
                ".....GGG........",
                ".....GGG........",
                "......G.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Melon3 = S("Melon3", true, CropPal,
                ".....ll.........",
                "....llll........",
                ".....ll.........",
                "...llllll.......",
                "....llll........",
                "..GGGGGGGG......",
                ".GGggGGggGG.....",
                ".GggGgggGgG.....",
                ".GggGgggGgG.....",
                ".GGggGGggGG.....",
                "..GGGGGGGG......",
                "...GG..GG.......",
                "................",
                "................",
                "................",
                "................");

            // --- Mochi Rice (winter) ---
            MochiRice0 = S("MochiRice0", true, CropPal,
                ".....ww.........",
                "....wwww........",
                ".....ww.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            MochiRice1 = S("MochiRice1", true, CropPal,
                ".....ll.........",
                "....llll........",
                ".....ll.........",
                ".....ww.........",
                "....wwww........",
                ".....ww.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            MochiRice2 = S("MochiRice2", true, CropPal,
                ".....ll.........",
                "....llll........",
                ".....ll.........",
                ".....ww.........",
                "....wwww........",
                ".....ww.........",
                "....wwww........",
                "...wwBww........",
                "....wwww........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            MochiRice3 = S("MochiRice3", true, CropPal,
                ".....ll.........",
                "....llll........",
                ".....ll.........",
                "...wwwwww.......",
                "..wwwwwwww......",
                "..wwBwwwwBw.....",
                "..wwwwwwww......",
                "..wwwwwwww......",
                "...wwwwww.......",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            // --- Fish (16x10, swimming left) ---
            Goldfish = S("Goldfish", true, FishPal,
                "......oooooo....",
                "....oooooooooo..",
                "..oooooooooooo..",
                ".ooooooowwoooo..",
                "ooooooookwoooo..",
                ".ooooooowwoooo..",
                "..oooooooooooo..",
                "...oooooooooo...",
                "....oooo.o.oo...",
                ".........oo.....");

            BubbleFish = S("BubbleFish", true, FishPal,
                "......ww........",
                "....uuuuuu......",
                "...uuuuuuuu.....",
                "..uuuuuuwwuu....",
                ".uuuuuuwkwuuu...",
                "..uuuuuwwuuu....",
                "...uuuuuuuu.....",
                "....uuuu.uu.....",
                ".....uu..u......",
                "................");

            SakuraFish = S("SakuraFish", true, FishPal,
                "......r.r........",
                "....rrrrrrrr.....",
                "..rrrrrrrrrrr....",
                ".rrrrrrwwrrrr....",
                "rrrrrrrkwrrrr....",
                ".rrrrrrwwrrrr....",
                "..rrrrrrrrrrr....",
                "...rrrrrrrr......",
                "....rrrr.r.r.....",
                ".........r.......");

            // --- Eggs, kitchen & decor ---
            Egg = S("Egg", true, ItemPal,
                "................",
                "....wwww........",
                "...wwwwww.......",
                "..wwwwwwww......",
                "..wwwwwwww......",
                "..wwwwwwww......",
                "...wwwwww.......",
                "....wwww........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            KitchenTable = S("KitchenTable", true, TilePal,
                "................",
                "................",
                "................",
                "..dddddddddddd..",
                "..dccccccccccd..",
                "..dccyyccyyccd..",
                "..dddddddddddd..",
                "...d.dd..dd.d...",
                "...d.dd..dd.d...",
                "...d.dd..dd.d...",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Lantern = S("Lantern", true, TilePal,
                "................",
                ".....yyyyyy.....",
                ".....ycccyy.....",
                ".....yyyyyy.....",
                "......yy........",
                "......dd........",
                "......dd........",
                "......dd........",
                "......dd........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Gnome = S("Gnome", true, TilePal,
                "................",
                "......rr........",
                ".....rrrr.......",
                ".....rrrr.......",
                ".....ssss.......",
                ".....ssss.......",
                ".....wssw.......",
                "......ss........",
                "......ss........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Beehive = S("Beehive", true, TilePal,
                "................",
                "................",
                "......yy........",
                ".....yyyy.......",
                "....yyyyyy......",
                "....yccyyy......",
                "....yyyyyy......",
                "....yccyyy......",
                "....yyyyyy......",
                ".....yyyy.......",
                "......yy........",
                "................",
                "................",
                "................",
                "................",
                "................");

            Honey = S("Honey", true, ItemPal,
                "................",
                "..yyyyyyyyyy....",
                "..yyyccyyycy....",
                "..yccyyyccyy....",
                "..yyyyccyycy....",
                "..yyyccyyycy....",
                "..yyyyyyyyyy....",
                "..yyyyyyyyyy....",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            // --- Chickens (16x16, side view) ---
            Chicken0 = S("Chicken0", true, ChickenPal,
                "................",
                "................",
                "......ww........",
                ".....wwww.......",
                ".....wyyyw......",
                ".....wyyyw......",
                "....wwwwww......",
                "...wwwrwwww.....",
                "..wwwwwwwwww....",
                "..wwwwwwwwww....",
                "..wwwcwwcwww....",
                "...wwwwwwww.....",
                "....ww..ww......",
                ".....o..o.......",
                "................",
                "................");

            Chicken1 = S("Chicken1", true, ChickenPal,
                "................",
                "................",
                "......ww........",
                ".....wwww.......",
                ".....wyyyw......",
                ".....wyyyw......",
                "....wwwwww......",
                "...wwwrwwww.....",
                "..wwwwwwwwww....",
                "..wwwwwwwwww....",
                "..wwwcwwcwww....",
                "...wwwwwwww.....",
                "....ww..ww......",
                "......o..o......",
                "................",
                "................");

            Chicken2 = S("Chicken2", true, ChickenPal,
                "................",
                "................",
                "......ww........",
                ".....wwww.......",
                ".....wyyyw......",
                ".....wyyyw......",
                "....wwwwww......",
                "...wwwrwwww.....",
                "..wwwwwwwwww....",
                "..wwwwwwwwww....",
                "..wwwcwwcwww....",
                "...wwwwwwww.....",
                "...ww....ww.....",
                "..o......o......",
                "................",
                "................");

            ChickenPink0 = S("ChickenPink0", true, ChickenPinkPal,
                "................",
                "................",
                "......ww........",
                ".....wwww.......",
                ".....wyyyw......",
                ".....wyyyw......",
                "....wwwwww......",
                "...wwwrwwww.....",
                "..wwwwwwwwww....",
                "..wwwwwwwwww....",
                "..wwwcwwcwww....",
                "...wwwwwwww.....",
                "....ww..ww......",
                ".....o..o.......",
                "................",
                "................");

            ChickenPink1 = S("ChickenPink1", true, ChickenPinkPal,
                "................",
                "................",
                "......ww........",
                ".....wwww.......",
                ".....wyyyw......",
                ".....wyyyw......",
                "....wwwwww......",
                "...wwwrwwww.....",
                "..wwwwwwwwww....",
                "..wwwwwwwwww....",
                "..wwwcwwcwww....",
                "...wwwwwwww.....",
                "....ww..ww......",
                "......o..o......",
                "................",
                "................");

            ChickenPink2 = S("ChickenPink2", true, ChickenPinkPal,
                "................",
                "................",
                "......ww........",
                ".....wwww.......",
                ".....wyyyw......",
                ".....wyyyw......",
                "....wwwwww......",
                "...wwwrwwww.....",
                "..wwwwwwwwww....",
                "..wwwwwwwwww....",
                "..wwwcwwcwww....",
                "...wwwwwwww.....",
                "...ww....ww.....",
                "..o......o......",
                "................",
                "................");

            // --- Sky objects ---
            Sun = S("Sun", SkyPal,
                "................",
                ".......yy.......",
                "......yyyy......",
                ".....yyyyyy.....",
                ".....yccyyy.....",
                ".....yyyyyy.....",
                "......yyyy......",
                ".......yy.......",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Moon = S("Moon", SkyPal,
                "......mmm.......",
                ".....mmmmmm.....",
                "....mmmmmmmm....",
                "...mmmmmmmmmm...",
                "...mmmmmmccmm...",
                "...mmmmmmmmmm...",
                "....mmmmmmmm....",
                ".....mmmmmm.....",
                "......mmm.......",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Star = S("Star", SkyPal,
                "......n.........",
                ".......n........",
                ".nnnnnnnnnn.....",
                ".......n........",
                "......n.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Cloud = S("Cloud", SkyPal,
                "................",
                "......mmm.......",
                "....mmmmmmm.....",
                "...mmmmmmmmmm...",
                "...mmmmmmmmmm...",
                "....mmmmmmmm....",
                "......mmmm......",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Zzz = S("Zzz", SkyPal,
                "......m.........",
                ".......m........",
                ".....mm.........",
                "......mm........",
                "....mmm.........",
                ".....mmm........",
                "...mmmm.........",
                "..mmmmm.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            // --- Shop stand ---
            ShopStand = S("ShopStand", true, TilePal,
                "..pppppppppppp..",
                ".pppppppppppppp.",
                ".pppppppppppppp.",
                ".pppppppppppppp.",
                ".pppppppppppppp.",
                ".pppppppppppppp.",
                "..d...........d.",
                "..ddddddddddddd.",
                "..d..........d..",
                "..d..p....p..d..",
                "..d..p....p..d..",
                "..d..........d..",
                "..ddddddddddddd.",
                "................",
                "................",
                "................");

            QuestBoard = S("QuestBoard", true, TilePal,
                "................",
                "...dddddddddd....",
                "..dccccccccccd...",
                "..dccccccccccd...",
                "..dccrrrccrrcd...",
                "..dccccccccccd...",
                "..dccrrcccrrcd...",
                "..dccccccccccd...",
                "..dccccccccccd...",
                "...dddddddddd....",
                "...dd....dd......",
                "...dd....dd......",
                "................",
                "................",
                "................",
                "................");

            LockedTile = S("LockedTile", TilePal,
                "gggggggggggggggg",
                "gggggggggggggggg",
                "gggggggggggggggg",
                "g..dd...........",
                "g..dd..ddd......",
                "g..ddddd........",
                "g...dd..........",
                "g...dd..........",
                "g................",
                "g................",
                "g................",
                "g................",
                "g................",
                "g................",
                "g................",
                "g................");

            Deed = S("Deed", ItemPal,
                "................",
                "..cccccccccc....",
                "..cwwwwwwwwc....",
                "..cwrwwrwwrc....",
                "..cwwwwwwwwc....",
                "..cwwwwrwwwc....",
                "..cwwwwwwwwc....",
                "..cccccccccc....",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            // --- Items ---
            Coin = S("Coin", ItemPal,
                ".....yyy........",
                "....yyyyy.......",
                "...yyccyyy......",
                "...ycccyyy......",
                "...yyccyyy......",
                "....yyyyy.......",
                ".....yyy........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            Heart = SpriteFactory.HeartSprite(Color.white);
            HeartPink = SpriteFactory.HeartSprite(Palette.PetalPink);
            Sparkle = S("Sparkle", ItemPal,
                "................",
                "......w.........",
                "......w.........",
                "..w..www..w.....",
                "...wwwww........",
                "..wwwwwww.......",
                "....wwwww.......",
                "....w...w.......",
                "......w.........",
                "......w.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            WaterDrop = S("WaterDrop", ItemPal,
                "......W.........",
                ".....WWW........",
                "....WWWWW.......",
                "...WWWWWWW......",
                "..WWWWWWWWW.....",
                "..WWWWWWWWW.....",
                "...WWWWWWW......",
                "....WWWWW.......",
                ".....WWW........",
                "......W.........",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            MusicNote = S("MusicNote", ItemPal,
                ".....pp.........",
                ".....pp.........",
                ".....pp.........",
                ".....pp.........",
                ".....pppppp.....",
                ".....pppppppp...",
                ".....ppppppp....",
                ".....pppppp.....",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................",
                "................");

            HoeIcon = S("HoeIcon", ItemPal,
                "..ddd...........",
                "..ddd...........",
                "..ddd...........",
                "..ddd...........",
                "..ddd...........",
                "..ddd...........",
                "..ddd...........",
                "..ddd...........",
                "..ddd...........",
                "..ddd...........",
                "..ddd...........",
                "..ddd...........",
                ".dddd...........",
                ".dddd...........",
                "................",
                "................");

            CanIcon = S("CanIcon", ItemPal,
                "..bbbbbbbb......",
                "..bbbbbbbb......",
                "..bWWWWWWb......",
                "..bWWWWWWb......",
                "..bbbbbbbb......",
                "..bbbbbbbb......",
                ".bbbbbbbbbb.....",
                ".bbbbbbbbbb.....",
                ".bbbbbbbbbb.....",
                "..bbbbbbbb......",
                "..ddbbbbdd......",
                "..dd....dd......",
                "................",
                "................",
                "................",
                "................");

            HandIcon = S("HandIcon", ItemPal,
                ".......c........",
                ".......c........",
                "....cccccc......",
                "...ccccc........",
                "...ccccc........",
                "...cccc.........",
                "...cccc.........",
                "..cccc..........",
                "..cccc..........",
                "..cccc..........",
                "..cc............",
                "................",
                "................",
                "................",
                "................",
                "................");

            // Seed packet icons (reuse crop art, 12x12 inside packet bg drawn in UI)
            CropSprites = new Sprite[6, 4]
            {
                { Strawberry0, Strawberry1, Strawberry2, Strawberry3 },
                { Blueberry0, Blueberry1, Blueberry2, Blueberry3 },
                { Pumpkitten0, Pumpkitten1, Pumpkitten2, Pumpkitten3 },
                { Sakura0, Sakura1, Sakura2, Sakura3 },
                { Melon0, Melon1, Melon2, Melon3 },
                { MochiRice0, MochiRice1, MochiRice2, MochiRice3 },
            };
        }

        static Sprite S(string name, Dictionary<char, Color> pal, params string[] rows)
        {
            return S(name, false, pal, rows);
        }

        static readonly Color OutlineColor = new Color(0.36f, 0.27f, 0.33f, 0.88f);


        static Sprite S(string name, bool outline, Dictionary<char, Color> pal, params string[] rows)
        {
            var ps = PixelSprite.From(name, rows, pal);
            if (outline) ps = ps.Outlined(OutlineColor);
            return SpriteFactory.ToSprite(ps);
        }
    }
}
